routes/backend.php
<?php

Route::group(['middleware' => ['auth', 'isAdmin'], 'namespace' => 'Dashboard'], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::resource('/users', 'UserController');
    Route::resource('/products', 'ProductController');
    Route::resource('/orders', 'OrderController');
});

routes/web.php
<?php

use App\Product;
use Gloudemans\Shoppingcart\Facades\Cart;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register' => false]);

Route::get('/', 'HomeController@index')->name('home');

Route::get('/products', 'ProductController@index')->name('products');
Route::get('/products/{product}', 'ProductController@details')->name('product');
Route::get('/cart', 'CartController@cart')->name('cart');
Route::get('/profile', 'UserController@profile')->name('profile')->middleware(['auth', 'isUser']);


// Auth routes
Route::post('/user_login', 'AuthController@login')->name('user-login');
Route::post('/user_register', 'AuthController@register')->name('user-register');
Route::post('/user_logout', 'AuthController@logout')->name('user-logout');

Route::get('/check_qty', 'CartController@checkQty')->name('check-qty');
Route::get('/products', 'ProductController@index')->name('products');
Route::get('/products/{product}', 'ProductController@details')->name('product');
Route::post('/checkout', 'OrderController@checkout')->name('checkout');

app/Product.php
<?php

namespace App;

use App\Traits\Sluggable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use Sluggable, SoftDeletes;

    protected $fillable = ['name', 'slug', 'price', 'description', 'quantity'];

    public function sluggable()
    {
        return [
            'source' => $this->name,
            'column_name' => 'name',
        ];
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function orders()
    {
        return $this->belongsToMany('App\Order')->withPivot('quantity', 'unit_price', 'total_price');
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Order;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{

    public function index()
    {
        $count = Order::whereDate('created_at', '=', date('Y-m-d'))->count();
        return view('dashboard.home', compact('count'));
    }
}

app/Http/Controllers/Dashboard/OrderController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Order;
use Illuminate\Http\Request;
use App\Http\Requests\OrderRequest;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Lang;
use App\Repositories\Dashboard\OrderRepository;

class OrderController extends Controller
{
    public $order_repo;
    public function __construct(OrderRepository $order_repo)
    {
        $this->order_repo = $order_repo;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = $this->order_repo->all();
        return view('dashboard.order.index', compact('orders') );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        return view('dashboard.order.show', compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        return view('dashboard.order.edit', compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(OrderRequest $request, Order $order)
    {
        $validated_data = $request->validated();
        $this->order_repo->update($order, $validated_data);
        return redirect()->route('orders.index')->with('success', Lang::get('message.object.update', ['object' => 'Order']));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        $this->order_repo->delete($order);
        return redirect()->route('orders.index')->with('success', Lang::get('message.object.delete', ['object' => 'Order']));
    }
}

app/Http/Controllers/Dashboard/OrderProductController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Order;
use Illuminate\Http\Request;
use App\Http\Requests\OrderRequest;
use App\Http\Controllers\Controller;
use App\OrderProduct;
use Illuminate\Support\Facades\Lang;
use App\Repositories\Dashboard\OrderRepository;

class OrderProductController extends Controller
{

    public function edit(Order $order)
    {
        return view('dashboard.order_product.edit', compact('order'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Order $order, $order_product_id, Request $request)
    {
        $quantity = (int)$request->get('quantity');
        
        $order_product = OrderProduct::where('id', $order_product_id)->first();
        if($order_product) {
            $substracted_subtotal = $order->subtotal - $order_product->total_price;

            $updated_o_p_total_price = $quantity * $order_product->unit_price;
    
            //updating order_product's qty and total_price
            $order_product->quantity = $quantity;
            $order_product->total_price = $updated_o_p_total_price;
            $order_product->save();
    
            //updating order's subtotal and total price
            $order->subtotal = $substracted_subtotal + $updated_o_p_total_price;
    
            //
            $order->total = $substracted_subtotal + $updated_o_p_total_price;
            $order->save();
            
            return redirect()->route('orders.products.edit', $order->order_no)->with('success', Lang::get('message.object.update', ['object' => 'Order Product']));
        } else {

        }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order, $order_product_id)
    {
        $order_product = OrderProduct::where('id', $order_product_id)->first();
        if($order_product) {
            
            //updating order's subtotal and total price
            $order->subtotal -= $order_product->total_price;
            $order->total -= $order_product->total_price;
            $order->save();

            $order_product->delete();
            return redirect()->route('orders.products.edit', $order->order_no)->with('success', Lang::get('message.object.delete', ['object' => 'Order Product']));
        }
    }
}

app/Http/Controllers/Dashboard/ProductController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Dashobard\ProductRequest;
use Illuminate\Support\Facades\Lang;
use App\Repositories\Dashboard\ProductRepository;

class ProductController extends Controller
{
    public $product_repo;
    public function __construct(ProductRepository $product_repo)
    {
        $this->product_repo = $product_repo;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = $this->product_repo->all();
        return view('dashboard.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        $validated_data = $request->validated();
        $this->product_repo->store($validated_data);
        return redirect()->route('products.index')->with('success', Lang::get('message.object.create', ['object' => 'Product']));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('dashboard.product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('dashboard.product.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, Product $product)
    {
        $validated_data = $request->validated();
        $this->product_repo->update($product, $validated_data);
        return redirect()->route('products.index')->with('success', Lang::get('message.object.update', ['object' => 'Product']));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $this->product_repo->delete($product);
        return redirect()->route('products.index')->with('success', Lang::get('message.object.delete', ['object' => 'Product']));
    }
}

app/Http/Controllers/Dashboard/UserController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Lang;
use App\Repositories\Dashboard\UserRepository;
use App\User;

class UserController extends Controller
{
    public $user_repo;
    public function __construct(UserRepository $user_repo)
    {
        $this->user_repo = $user_repo;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = $this->user_repo->customers();
        return view('dashboard.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);
        $this->user_repo->store($validatedData);
        return redirect()->route('users.index')->with('success', Lang::get('message.object.create', ['object' => 'user']));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('dashboard.user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $validatedData = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email,' . $user->id],
        ]);
        $this->user_repo->update( $user, $validatedData );
        return redirect()->route('users.index')->with('success', Lang::get('message.object.update', ['object' => 'user']));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $this->user_repo->delete($user);
        return redirect()->route('users.index')->with('success', Lang::get('message.object.delete', ['object' => 'user']));
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;

class ProductController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        // $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $products = Product::paginate(10);
        return view('front.products', compact('products'));
    }

    public function details(Product $product)
    {
        return view('front.product', compact('product'));
    }
}

resources/views/dashboard/product/create.blade.php
@extends('adminlte::page')

@section('css')
<link rel="stylesheet" href="{{asset('css/trix.css')}}">
<style>
  trix-toolbar .trix-button-row .trix-button-group--file-tools {
    display: none;
  }
</style>
@stop

@section('content_header')

@stop

@section('content')

<div class="row pb-4">
  <div class="mt-3 col-12 offset-sm-2 col-sm-8 offset-lg-2 col-lg-8">
    <div class="card card-dark">
      <div class="card-header">
        <h3 class="card-title font-weight-light">Add New Product</h3>
      </div>

      <form role="form" method="POST" action="{{route('products.store')}}">
        @csrf
        <div class="card-body pb-1">

          
          <!-- name -->
          <div class="form-group">
            <label class="font-weight-light" for="name">name </label><span class="text-danger ml-1">*</span>
            <input type="text" class="form-control" id="name" name="name" value="{{old('name')}}" placeholder="Enter Product Name">
            @if ($errors->has('name'))
            <span class="help-block text-danger">
              <strong>{{ $errors->first('name') }}</strong>
            </span>
            @endif
          </div>

          <!-- price -->
          <div class="form-group">
            <label class="font-weight-light" for="price">Price </label><span class="text-danger ml-1">*</span>
            <input type="text" class="form-control" id="price" name="price" value="{{old('price')}}" placeholder="Enter Price">
            @if ($errors->has('price'))
            <span class="help-block text-danger">
              <strong>{{ $errors->first('price') }}</strong>
            </span>
            @endif
          </div>

          <!-- description -->
          <div class="form-group">
            <label class="font-weight-light" for="description">description</label>
            <input id="y" id="description" type="hidden" value="{{old('description')}}" name="description">
            <trix-editor input="y"></trix-editor>
            @if ($errors->has('description'))
            <span class="help-block text-danger">
              <strong>{{ $errors->first('description') }}</strong>
            </span>
            @endif
          </div>

          <!-- quantity -->
          <div class="form-group">
            <label class="font-weight-light" for="quantity">Stock Count </label><span class="text-danger ml-1">*</span>
            <input type="number" min="0" class="form-control" id="quantity" name="quantity" value="{{old('quantity')}}" placeholder="Enter Stock Quantity">
            @if ($errors->has('quantity'))
            <span class="help-block text-danger">
              <strong>{{ $errors->first('quantity') }}</strong>
            </span>
            @endif
          </div>

          <div class="form-group mt-5 text-center">
            <button type="submit" class="btn btn-primary mr-2">Create Product</button>
            <a class="btn btn-outline-primary" href="{{route('products.index')}}">Cancel</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

@stop

@section('js')
<script src="{{asset('js/trix.js')}}"></script>
@endsection

resources/views/dashboard/product/edit.blade.php
@extends('adminlte::page')

@section('css')
<link rel="stylesheet" href="{{asset('css/trix.css')}}">
<style>
    trix-toolbar .trix-button-row .trix-button-group--file-tools {
        display: none;
    }
</style>
@stop

@section('content_header')

@stop

@section('content')

<div class="row pb-4">
    <div class="mt-3 col-12 offset-sm-2 col-sm-8 offset-lg-2 col-lg-8">
        <div class="card card-dark">
            <div class="card-header">
                <h3 class="card-title font-weight-light">Edit Product</h3>
            </div>

            <form role="form" method="POST" action="{{route('products.update', $product->slug)}}">
                @method('put')
                @csrf
                <div class="card-body pb-1">

                    <!-- name -->
                    <div class="form-group">
                        <label class="font-weight-light" for="name">name </label><span class="text-danger ml-1">*</span>
                        <input type="text" class="form-control" id="name" name="name" value="{{$product->name}}" placeholder="Enter Product Name">
                        @if ($errors->has('name'))
                        <span class="help-block text-danger">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                        @endif
                    </div>

                    <!-- price -->
                    <div class="form-group">
                        <label class="font-weight-light" for="price">Price </label><span class="text-danger ml-1">*</span>
                        <input type="text" class="form-control" id="price" name="price" value="{{$product->price}}" placeholder="Enter Price">
                        @if ($errors->has('price'))
                        <span class="help-block text-danger">
                            <strong>{{ $errors->first('price') }}</strong>
                        </span>
                        @endif
                    </div>

                    <!-- description -->
                    <div class="form-group">
                        <label class="font-weight-light" for="description">description</label>
                        <input id="y" id="description" type="hidden" value="{!!$product->description!!}" name="description">
                        <trix-editor input="y"></trix-editor>
                        @if ($errors->has('description'))
                        <span class="help-block text-danger">
                            <strong>{{ $errors->first('description') }}</strong>
                        </span>
                        @endif
                    </div>

                    <!-- quantity -->
                    <div class="form-group">
                        <label class="font-weight-light" for="quantity">Stock Count </label><span class="text-danger ml-1">*</span>
                        <input type="number" min="0" class="form-control" id="quantity" name="quantity" value="{{$product->quantity}}" placeholder="Enter Product quantity">
                        @if ($errors->has('quantity'))
                        <span class="help-block text-danger">
                            <strong>{{ $errors->first('quantity') }}</strong>
                        </span>
                        @endif
                    </div>

                    <div class="form-group mt-5 text-center">
                        <button type="submit" class="btn btn-dark mr-2">Create Product</button>
                        <a class="btn btn-outline-dark" href="{{route('products.index')}}">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@stop

@section('js')
<script src="{{asset('js/trix.js')}}"></script>
@endsection

resources/views/dashboard/product/index.blade.php
@extends('adminlte::page')

@section('css')
@stop

@section('content_header')

@stop

@section('content')
@include('dashboard.modal.deletemodal')

@if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif
<div class="row pb-4">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header py-4">
                <div class="card-tools mr-0">
                    <a href="{{route('products.create')}}" class="btn btn-dark">Create New Product</a>
                </div>
                <h3 class="font-weight-light">products</h3>
            </div>
            <!-- /.card-header -->
            @if($products->isNotEmpty())
            <div class="card-body table-responsive">
                <table id="productstable" class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Name</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($products as $key=>$product)
                        <tr>
                            <th>{{ $products->firstItem() + $key }}</th>
                            <td> <a href="{{route('products.show', $product->slug)}}">{{$product->name}}</a> </td>
                            <td><a href="{{route('products.edit', $product->slug)}}" class="btn btn-transparent py-0"><i class="fas fa-edit text-dark"></i></a></td>
                            <td><button class="btn btn-transparent py-0" href="#deleteModalCenter" onclick="deleteData('<?php echo route('products.destroy', $product->slug) ?>')" data-toggle="modal"><i class="fas fa-trash text-dark"></i></button></td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $products->links() }}
            </div>
            @else
            <div class="text-center">
                There's no Product.
            </div>
            @endif
            <!-- /.card-body -->
        </div>
    </div>

    

    @stop

    @section('js')
    <script>
        function deleteData(route) {
            $(".deleteForm").attr('action', route);
            $("#deleteModalCenter").toggle();
            }        

        $(function() {
            
            $('#productstable').DataTable({
                responsive: true,
                searching: false,
                info: false,
                paging: false,
                "aaSorting": [],
                "columnDefs": [

                    {
                        "orderable": false,
                        "targets": 3
                    },
                    {
                        "orderable": false,
                        "targets": 4
                    },
                ]
            });
        });
    </script>

    @endsection

resources/views/dashboard/product/show.blade.php
@extends('adminlte::page')

@section('css')
@stop

@section('content_header')

@stop

@section('content')

<div class="row pb-4">
    <div class="offset-md-2 col-md-8 mt-3">
        <div class="card card-dark">
            <div class="card-header">
                <h3 class="card-title font-weight-light">Product Details</h3>
            </div>

            <div class="card-body">

                <div class="form-group mb-4">
                    <h5>{{$product->name}}</h5>
                </div>

                <div class="form-group mb-4 row">
                    <label class="font-weight-light col-sm-5">Stock Count</label>
                    <div class="col-sm-7">{{ $product->quantity }}</div>
                </div>

                <div class="form-group mb-4 row">
                    <label class="font-weight-light col-sm-5">Price</label>
                    <div class="col-sm-7">{{ number_format($product->price) }} MMK</div>
                </div>

                <div class="form-group mb-4 row">
                    <label class="font-weight-light col-sm-5">description</label>
                    <div class="col-sm-7">{!! $product->description !!}</div>
                </div>
                
            </div>

            <div class="card-footer bg-transparent border-top text-center">
                <a href="{{ route('products.index') }}" class="btn btn-dark">Back to Products List</a>
            </div>
        </div>
    </div>
</div>

@stop