routes/backend.php
<?php

Route::group(['middleware' => ['auth', 'isAdmin'], 'namespace' => 'Dashboard'], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::resource('/users', 'UserController');
    Route::resource('/products', 'ProductController');
    Route::resource('/orders', 'OrderController');
});

routes/web.php
<?php

use App\Product;
use Gloudemans\Shoppingcart\Facades\Cart;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['register' => false]);

Route::get('/', 'HomeController@index')->name('home');

Route::get('/products', 'ProductController@index')->name('products');
Route::get('/products/{product}', 'ProductController@details')->name('product');
Route::get('/cart', 'CartController@cart')->name('cart');
Route::get('/profile', 'UserController@profile')->name('profile')->middleware(['auth', 'isUser']);


// Auth routes
Route::post('/user_login', 'AuthController@login')->name('user-login');
Route::post('/user_register', 'AuthController@register')->name('user-register');
Route::post('/user_logout', 'AuthController@logout')->name('user-logout');

Route::get('/check_qty', 'CartController@checkQty')->name('check-qty');
Route::get('/products', 'ProductController@index')->name('products');
Route::get('/products/{product}', 'ProductController@details')->name('product');
Route::post('/checkout', 'OrderController@checkout')->name('checkout');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Order extends Model
{
    public $guarded = [];

    public function getRouteKeyName()
    {
        return 'order_no';
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function products()
    {
        return $this->belongsToMany('App\Product')->withTrashed()->withPivot('id', 'quantity', 'unit_price', 'total_price');
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Order;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{

    public function index()
    {
        $count = Order::whereDate('created_at', '=', date('Y-m-d'))->count();
        return view('dashboard.home', compact('count'));
    }
}

app/Http/Controllers/Dashboard/OrderController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Order;
use Illuminate\Http\Request;
use App\Http\Requests\OrderRequest;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Lang;
use App\Repositories\Dashboard\OrderRepository;

class OrderController extends Controller
{
    public $order_repo;
    public function __construct(OrderRepository $order_repo)
    {
        $this->order_repo = $order_repo;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = $this->order_repo->all();
        return view('dashboard.order.index', compact('orders') );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        return view('dashboard.order.show', compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        return view('dashboard.order.edit', compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(OrderRequest $request, Order $order)
    {
        $validated_data = $request->validated();
        $this->order_repo->update($order, $validated_data);
        return redirect()->route('orders.index')->with('success', Lang::get('message.object.update', ['object' => 'Order']));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        $this->order_repo->delete($order);
        return redirect()->route('orders.index')->with('success', Lang::get('message.object.delete', ['object' => 'Order']));
    }
}

app/Http/Controllers/Dashboard/OrderProductController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Order;
use Illuminate\Http\Request;
use App\Http\Requests\OrderRequest;
use App\Http\Controllers\Controller;
use App\OrderProduct;
use Illuminate\Support\Facades\Lang;
use App\Repositories\Dashboard\OrderRepository;

class OrderProductController extends Controller
{

    public function edit(Order $order)
    {
        return view('dashboard.order_product.edit', compact('order'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Order $order, $order_product_id, Request $request)
    {
        $quantity = (int)$request->get('quantity');
        
        $order_product = OrderProduct::where('id', $order_product_id)->first();
        if($order_product) {
            $substracted_subtotal = $order->subtotal - $order_product->total_price;

            $updated_o_p_total_price = $quantity * $order_product->unit_price;
    
            //updating order_product's qty and total_price
            $order_product->quantity = $quantity;
            $order_product->total_price = $updated_o_p_total_price;
            $order_product->save();
    
            //updating order's subtotal and total price
            $order->subtotal = $substracted_subtotal + $updated_o_p_total_price;
    
            //
            $order->total = $substracted_subtotal + $updated_o_p_total_price;
            $order->save();
            
            return redirect()->route('orders.products.edit', $order->order_no)->with('success', Lang::get('message.object.update', ['object' => 'Order Product']));
        } else {

        }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order, $order_product_id)
    {
        $order_product = OrderProduct::where('id', $order_product_id)->first();
        if($order_product) {
            
            //updating order's subtotal and total price
            $order->subtotal -= $order_product->total_price;
            $order->total -= $order_product->total_price;
            $order->save();

            $order_product->delete();
            return redirect()->route('orders.products.edit', $order->order_no)->with('success', Lang::get('message.object.delete', ['object' => 'Order Product']));
        }
    }
}

app/Http/Controllers/Dashboard/ProductController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Dashobard\ProductRequest;
use Illuminate\Support\Facades\Lang;
use App\Repositories\Dashboard\ProductRepository;

class ProductController extends Controller
{
    public $product_repo;
    public function __construct(ProductRepository $product_repo)
    {
        $this->product_repo = $product_repo;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = $this->product_repo->all();
        return view('dashboard.product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        $validated_data = $request->validated();
        $this->product_repo->store($validated_data);
        return redirect()->route('products.index')->with('success', Lang::get('message.object.create', ['object' => 'Product']));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('dashboard.product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('dashboard.product.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, Product $product)
    {
        $validated_data = $request->validated();
        $this->product_repo->update($product, $validated_data);
        return redirect()->route('products.index')->with('success', Lang::get('message.object.update', ['object' => 'Product']));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $this->product_repo->delete($product);
        return redirect()->route('products.index')->with('success', Lang::get('message.object.delete', ['object' => 'Product']));
    }
}

app/Http/Controllers/Dashboard/UserController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Lang;
use App\Repositories\Dashboard\UserRepository;
use App\User;

class UserController extends Controller
{
    public $user_repo;
    public function __construct(UserRepository $user_repo)
    {
        $this->user_repo = $user_repo;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = $this->user_repo->customers();
        return view('dashboard.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);
        $this->user_repo->store($validatedData);
        return redirect()->route('users.index')->with('success', Lang::get('message.object.create', ['object' => 'user']));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('dashboard.user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $validatedData = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email,' . $user->id],
        ]);
        $this->user_repo->update( $user, $validatedData );
        return redirect()->route('users.index')->with('success', Lang::get('message.object.update', ['object' => 'user']));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $this->user_repo->delete($user);
        return redirect()->route('users.index')->with('success', Lang::get('message.object.delete', ['object' => 'user']));
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use App\Product;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\OrderRequest;
use Illuminate\Support\Facades\Auth;

class OrderController extends Controller
{
    public function checkout(OrderRequest $request)
    {
        $validated_data = $request->validated();
        if($validated_data['products']) {
            // return Auth::user();
            // create order
            $data = [
                'order_no' => 'FT-'.Carbon::now()->timestamp,
                'user_id' => Auth::user()->id,
                'phone' => $validated_data['phone'],
                'address' => $validated_data['address']
            ];
            $order = Order::create($data);
            $sub_total = 0;
            foreach($validated_data['products'] as $cart_product) {
                //create order product
                $product = Product::whereId($cart_product['id'])->first();
                if($product) {
                    $quantity = $cart_product['quantity'];
                    if($quantity <= $product->quantity) {
                        $unit_price = $product->price;
                        $total_price = $unit_price * $quantity;
                        $sub_total += $total_price;
                        DB::table('order_product')->insert([
                            'order_id' => $order->id,
                            'product_id' => $product->id,
                            'quantity' => $quantity,
                            'unit_price' => $unit_price,
                            'total_price' => $total_price,
                        ]);
                        $product->quantity -= $quantity;
                        $product->save();
                    }
                }
            }
            $order->total = $sub_total;
            $order->save();
            return 'success';
            // return redirect()->route('profile');
        }
    }
}

resources/views/dashboard/order/edit.blade.php
@extends('adminlte::page')

@section('css')
<link rel="stylesheet" href="{{asset('css/trix.css')}}">
<style>
    trix-toolbar .trix-button-row .trix-button-group--file-tools {
        display: none;
    }
</style>
@stop

@section('content_header')

@stop

@section('content')

<div class="row pb-4">
    <div class="mt-3 col-12 offset-sm-2 col-sm-8 offset-lg-2 col-lg-8">
        <div class="card card-dark">
            <div class="card-header">
                <h3 class="card-title font-weight-light">Edit Order</h3>
            </div>

            <form role="form" method="POST" action="{{route('orders.update', $order->order_no)}}" enctype="multipart/form-data">
                @method('put')
                @csrf
                <div class="card-body pb-1">

                    <!-- f name -->
                    <div class="form-group">
                        <label class="font-weight-light" for="first_name">First Name </label><span class="text-danger ml-1">*</span>
                        <input type="text" class="form-control" id="first_name" name="first_name" value="{{$order->first_name}}" placeholder="Enter order first_Name">
                        @if ($errors->has('first_name'))
                        <span class="help-block text-danger">
                            <strong>{{ $errors->first('first_name') }}</strong>
                        </span>
                        @endif
                    </div>

                    <!-- email -->
                    <div class="form-group">
                        <label class="font-weight-light" for="email">email </label><span class="text-danger ml-1">*</span>
                        <input type="email" class="form-control" id="email" name="email" value="{{$order->email}}" placeholder="Enter order email">
                        @if ($errors->has('email'))
                        <span class="help-block text-danger">
                            <strong>{{ $errors->first('email') }}</strong>
                        </span>
                        @endif
                    </div>

                    <!-- phone -->
                    <div class="form-group">
                        <label class="font-weight-light" for="phone">Phone </label><span class="text-danger ml-1">*</span>
                        <input type="text" class="form-control" id="phone" name="phone" value="{{$order->phone}}" placeholder="Enter order phone">
                        @if ($errors->has('phone'))
                        <span class="help-block text-danger">
                            <strong>{{ $errors->first('phone') }}</strong>
                        </span>
                        @endif
                    </div>

                    <!-- address -->
                    <div class="form-group">
                        <label class="font-weight-light" for="address">Address </label><span class="text-danger ml-1">*</span>
                        <input type="text" class="form-control" id="address" name="address" value="{{$order->address}}" placeholder="Enter order address">
                        @if ($errors->has('address'))
                        <span class="help-block text-danger">
                            <strong>{{ $errors->first('address') }}</strong>
                        </span>
                        @endif
                    </div>

                    <div class="form-group mt-5 text-center">
                        <button type="submit" class="btn btn-primary mr-2">Create order</button>
                        <a class="btn btn-outline-primary" href="{{route('orders.index')}}">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@stop

@section('js')
<script src="{{asset('js/trix.js')}}"></script>
@endsection

resources/views/dashboard/order/index.blade.php
@extends('adminlte::page')

@section('css')
@stop

@section('content_header')

@stop

@section('content')
@include('dashboard.modal.deletemodal')

@if (session('success'))
<div class="alert alert-success">
    {{ session('success') }}
</div>
@endif
<div class="row pb-4">
    <div class="col-sm-12">
        @if($orders->isNotEmpty())
        <div class="card">
            <!-- /.card-header -->

            <div class="card-body table-responsive">
                <table id="orderstable" class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Order No.</th>
                            <th>Customer Name</th>
                            <th>Phone</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($orders as $key=>$order)
                        <tr>
                            <td>{{ $orders->firstItem() + $key }}</td>
                            <td> <a href="{{route('orders.show', $order->order_no)}}">{{$order->order_no}}</a> </td>
                            <td>{{$order->user->name}}</td>
                            <td>{{$order->phone}}</td>
                            <td>{{date_format($order->created_at, 'd/M/Y')}}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{$orders->links()}}
            </div>

            <!-- /.card-body -->
        </div>
        @else
        <div class="text-center">
            There's no Orders.
        </div>
        @endif
    </div>



    @stop

    @section('js')
    <script>
        function deleteData(route) {
            $(".deleteForm").attr('action', route);
            $("#deleteModalCenter").toggle();
        }

        $(function() {

            $('#orderstable').DataTable({
                responsive: true,
                searching: false,
                info: false,
                paging: false,
                "aaSorting": [],
                "columnDefs": [{
                        "orderable": false,
                        "targets": 5
                    },
                    {
                        "orderable": false,
                        "targets": 7
                    },
                    {
                        "orderable": false,
                        "targets": 6
                    },
                ]
            });
        });
    </script>

    @endsection

resources/views/dashboard/order/show.blade.php
@extends('adminlte::page')

@section('css')
@stop

@section('content_header')

@stop

@section('content')

<div class="row pb-4">
    <div class="col-md-5 col-sm-12 mt-3">
        <div class="card card-dark">
            <div class="card-header">
                <h3 class="card-title font-weight-light">Order Details</h3>
            </div>

            <div class="card-body">

                <div class="form-group mb-4">
                    <h5>{{$order->order_no}}</h5>
                </div>

                <div class="form-group mb-4 row">
                    <label class="font-weight-light col-sm-5">Customer Name</label>
                    <div class="col-sm-7">{{ $order->user->name}}</div>
                </div>

                <div class="form-group mb-4 row">
                    <label class="font-weight-light col-sm-5">Eamil</label>
                    <div class="col-sm-7">{{ $order->user->email }}</div>
                </div>

                <div class="form-group mb-4 row">
                    <label class="font-weight-light col-sm-5">Phone</label>
                    <div class="col-sm-7">{{ $order->phone }}</div>
                </div>

                <div class="form-group mb-4 row">
                    <label class="font-weight-light col-sm-5">Address</label>
                    <div class="col-sm-7">{{ $order->address }}</div>
                </div>

            </div>

            <div class="card-footer bg-transparent border-top text-center">
                <a href="{{ route('orders.index') }}" class="btn btn-dark">Back to Orders List</a>
            </div>
        </div>
    </div>

    <div class="col-md-7 col-sm-12 mt-3">
        <div class="card card-dark">
            <div class="card-header">
                <h3 class="card-title font-weight-light">Order Products</h3>
            </div>

            <div class="card-body">
                <div class="form-group mb-4 row">
                    <div class="col-sm-1">No.</div>
                    <div class="col-sm-5">Name</div>
                    <div class="col-sm-2">Qty</div>
                    <div class="col-sm-2">Price</div>
                    <div class="col-sm-2">Total</div>
                </div>

                @foreach ($order->products as $key=>$product)
                <div class="form-group mb-4 row">
                    <div class="font-weight-light col-sm-1">{{$key+1}}</div>
                    <div class="font-weight-light col-sm-5">{{$product->name}}</div>
                    <div class="font-weight-light col-sm-2">{{$product->pivot->quantity}}</div>
                    <div class="font-weight-light col-sm-2">{{number_format($product->pivot->unit_price)}}</div>
                    <div class="font-weight-light col-sm-2">{{number_format($product->pivot->total_price)}}</div>
                </div>
                @endforeach
                <hr>
                <div class="form-group mb-4 row">
                    <div class="font-weight-light col-sm-10">SubTotal</div>
                    <div class="font-weight-light col-sm-2">{{number_format($order->total)}}</div>
                </div>
                <div class="form-group mb-4 row">
                    <div class="font-weight-light col-sm-10">Total</div>
                    <div class="font-weight-light col-sm-2">{{number_format($order->total)}}</div>
                </div>
            </div>
        </div>
    </div>
</div>

@stop